# Generated by Django 2.2.2 on 2019-06-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190605_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user_id',
        ),
    ]
