# Generated by Django 2.2.2 on 2019-06-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_images_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='start_date',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='stop_date',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
